image: ruby:2.5.7
before_script:
  - apt-g --no-riet update -qq && apt-get install -y -qq libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --without staging production
stages:
  - build

job_build:
  stage: build
  script:
    - RACK_ENV=test bundle exec rake