image: ruby:3.3.1

services:
  - docker:dind

variables:
  REGISTRY_URL: registry.gitlab.com/fiuba-memo2/ejemplos
  APP_NAME: telegram-bot-example
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  TEAM: docentes

stages:
  - build
  - package
  - deploy_test

sonarcloud-check:
  stage: build
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner

build_job:
  stage: build
  script:
    - gem install bundler -v 2.3.26 --no-document
    - bundle install --without staging production
    - APP_MODE=test bundle exec rake build_server
    - bundle exec rake version > VERSION.txt
  artifacts:
    paths:
      - VERSION.txt
      - reports/
    reports:
      junit: reports/spec/rspec.xml


package_job:
  stage: package
  image: docker:stable
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - VERSION=$(cat VERSION.txt)
    - echo $VERSION
    - docker build -f Dockerfile.prod --build-arg VERSION=$VERSION --build-arg GIT_COMMIT=$CI_COMMIT_SHORT_SHA -t $REGISTRY_URL/$APP_NAME:$VERSION .
    - docker tag $REGISTRY_URL/$APP_NAME:$VERSION $REGISTRY_URL/$APP_NAME:latest
    - docker push $REGISTRY_URL/$APP_NAME:$VERSION
    - docker push $REGISTRY_URL/$APP_NAME:latest
  only:
    - tags

deploy_test_job:
  stage: deploy_test
  image: nicopaez/kubectl:1.28.0
  environment: test
  script:
    - VERSION=$(cat VERSION.txt)
    - cp ${KUBECONFIG} $HOME/.kube/config
    - kubectl config set-context –current –namespace=${TEAM}-${CI_ENVIRONMENT_NAME}
    - kubectl apply -f infra/${CI_ENVIRONMENT_NAME}.configmap.yaml
    - kubectl set image deployment/telegrambot telegrambot=$REGISTRY_URL/$APP_NAME:$VERSION
  only:
    - tags