apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo2bot
  labels:
    app: memo2bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memo2bot
  template:
    metadata:
      labels:
        app: memo2bot
    spec:
      containers:
      - name: telegrambot
        image: registry.gitlab.com/fiuba-memo2/ejemplos/telegram-bot-example:0.0.16
        envFrom:
          - secretRef:
              name: botsecret
          - configMapRef:
              name: botconfig
